In [11]:
!#/usr/bin/env python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy

In [12]:
import numpy as np

def solve(basis_vectors, y):
    # Stack basis vectors into matrix A
    A = np.hstack(basis_vectors)

    # Problem 1: Check if y is in the span of the basis vectors
    rank_A = np.linalg.matrix_rank(A)
    augmented_matrix = np.hstack((A, y.reshape(-1, 1)))
    rank_augmented = np.linalg.matrix_rank(augmented_matrix)

    in_span = rank_A == rank_augmented
    print('Problem 1: Is y in the span of the basis vectors?', in_span)

    # Problem 2: Normalize the basis vectors
    normalized_basis = [v / np.linalg.norm(v) for v in basis_vectors]
    print('Problem 2: Normalized basis vectors:')
    for i, vec in enumerate(normalized_basis):
        print(f'Vector {i+1}: {vec}')

    # Problem 3: Use basis as columns of A
    A = np.hstack(basis_vectors)
    print('Problem 3: Matrix A using basis as columns:\n', A)
    # Problem 4: Use basis as rows for B
    B = A.T
    print('Problem 4: Matrix B using basis as columns:\n', B)

    # Problem 5: Find null space of A and B
    if rank_A < A.shape[1]:  # Null space exists only if rank < number of columns
        null_space_A = scipy.linalg.null_space(A)
        print('Problem 5: Null space of A:\n', null_space_A)
    else:
        print('Problem 5: Null space of A is trivial (only zero vector)')

    rank_B = np.linalg.matrix_rank(B)
    if rank_B < B.shape[1]:
        null_space_B = scipy.linalg.null_space(B)
        print('Null space of B:\n', null_space_B)
    else:
        print('Null space of B is trivial (only zero vector)')
    # Problem 6: Are columns of A independent or dependent?
    rank_A = np.linalg.matrix_rank(A)
    num_columns_A = A.shape[1]
    independent_A = rank_A == num_columns_A
    print(f'Problem 6: Columns of A are {"independent" if independent_A else "dependent"}')

    # Problem 7: Are columns of B independent or dependent?
    B = A.T  # Rows of A become columns of B
    rank_B = np.linalg.matrix_rank(B)
    num_columns_B = B.shape[1]
    independent_B = rank_B == num_columns_B
    print(f'Problem 7: Columns of B are {"independent" if independent_B else "dependent"}')

    # Problem 8: Dimension of the null space (Nullity)
    nullity_A = num_columns_A - rank_A
    nullity_B = num_columns_B - rank_B
    print(f'Problem 8: Dimension of null space of A: {nullity_A}')
    print(f'Problem 8: Dimension of null space of B: {nullity_B}')

    # Problem 9: Rank of A and B
    print(f'Problem 9: Rank of A: {rank_A}')
    print(f'Problem 9: Rank of B: {rank_B}')


In [13]:
#1
basis_vectors = [
    np.array([[7, 1]]).T,
    np.array([[0, 1]]).T
]

solve(basis_vectors, np.array([[1, 8]]).T)



Problem 1: Is y in the span of the basis vectors? True
Problem 2: Normalized basis vectors:
Vector 1: [[0.98994949]
 [0.14142136]]
Vector 2: [[0.]
 [1.]]
Problem 3: Matrix A using basis as columns:
 [[7 0]
 [1 1]]
Problem 4: Matrix B using basis as columns:
 [[7 1]
 [0 1]]
Problem 5: Null space of A is trivial (only zero vector)
Null space of B is trivial (only zero vector)
Problem 6: Columns of A are independent
Problem 7: Columns of B are independent
Problem 8: Dimension of null space of A: 0
Problem 8: Dimension of null space of B: 0
Problem 9: Rank of A: 2
Problem 9: Rank of B: 2


In [14]:
#2
basis_vectors = [
    np.array([[0, 8, 0, 3]]).T,
    np.array([[0, 8, 1, 0]]).T
]
y = np.array([[1, 0, 2, 2]]).T

solve(basis_vectors, y)


Problem 1: Is y in the span of the basis vectors? False
Problem 2: Normalized basis vectors:
Vector 1: [[0.        ]
 [0.93632918]
 [0.        ]
 [0.35112344]]
Vector 2: [[0.        ]
 [0.99227788]
 [0.12403473]
 [0.        ]]
Problem 3: Matrix A using basis as columns:
 [[0 0]
 [8 8]
 [0 1]
 [3 0]]
Problem 4: Matrix B using basis as columns:
 [[0 8 0 3]
 [0 8 1 0]]
Problem 5: Null space of A is trivial (only zero vector)
Null space of B:
 [[ 0.23597121 -0.97176005]
 [-0.11443476 -0.02778804]
 [ 0.91547804  0.22230432]
 [ 0.30515935  0.07410144]]
Problem 6: Columns of A are independent
Problem 7: Columns of B are dependent
Problem 8: Dimension of null space of A: 0
Problem 8: Dimension of null space of B: 2
Problem 9: Rank of A: 2
Problem 9: Rank of B: 2


In [15]:
#3
basis_vectors = [
    np.array([[1, 0, 0]]).T,
    np.array([[1, 1, 0]]).T,
    np.array([[1, 1, 1]]).T
]
y = np.array([[1, 4, 2]]).T

solve(basis_vectors, y)


Problem 1: Is y in the span of the basis vectors? True
Problem 2: Normalized basis vectors:
Vector 1: [[1.]
 [0.]
 [0.]]
Vector 2: [[0.70710678]
 [0.70710678]
 [0.        ]]
Vector 3: [[0.57735027]
 [0.57735027]
 [0.57735027]]
Problem 3: Matrix A using basis as columns:
 [[1 1 1]
 [0 1 1]
 [0 0 1]]
Problem 4: Matrix B using basis as columns:
 [[1 0 0]
 [1 1 0]
 [1 1 1]]
Problem 5: Null space of A is trivial (only zero vector)
Null space of B is trivial (only zero vector)
Problem 6: Columns of A are independent
Problem 7: Columns of B are independent
Problem 8: Dimension of null space of A: 0
Problem 8: Dimension of null space of B: 0
Problem 9: Rank of A: 3
Problem 9: Rank of B: 3


In [16]:
#4
basis_vectors = [
    np.array([[1, 0, 0]]).T,
    np.array([[3, 0, 0]]).T,
    np.array([[0, 1, 0]]).T,
    np.array([[1, 0, 1]]).T,
    np.array([[1, 1, 1]]).T
]
y = np.array([[1, 2, 3]]).T

solve(basis_vectors, y)


Problem 1: Is y in the span of the basis vectors? True
Problem 2: Normalized basis vectors:
Vector 1: [[1.]
 [0.]
 [0.]]
Vector 2: [[1.]
 [0.]
 [0.]]
Vector 3: [[0.]
 [1.]
 [0.]]
Vector 4: [[0.70710678]
 [0.        ]
 [0.70710678]]
Vector 5: [[0.57735027]
 [0.57735027]
 [0.57735027]]
Problem 3: Matrix A using basis as columns:
 [[1 3 0 1 1]
 [0 0 1 0 1]
 [0 0 0 1 1]]
Problem 4: Matrix B using basis as columns:
 [[1 0 0]
 [3 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]]
Problem 5: Null space of A:
 [[-0.4597804  -0.82982045]
 [ 0.15326013  0.27660682]
 [ 0.50501265 -0.27981344]
 [ 0.50501265 -0.27981344]
 [-0.50501265  0.27981344]]
Null space of B is trivial (only zero vector)
Problem 6: Columns of A are dependent
Problem 7: Columns of B are independent
Problem 8: Dimension of null space of A: 2
Problem 8: Dimension of null space of B: 0
Problem 9: Rank of A: 3
Problem 9: Rank of B: 3


In [17]:
#5
basis_vectors = [
    np.array([[1, 0, 0, 0, 3]]).T,
    np.array([[1, 0, 0, 1, 3]]).T,
    np.array([[0, 1, 0, 1, 3]]).T,
    np.array([[0, 0, 1, 1, 0]]).T
]
y = np.array([[1, 0, 0, 1, 6]]).T

solve(basis_vectors, y)


Problem 1: Is y in the span of the basis vectors? False
Problem 2: Normalized basis vectors:
Vector 1: [[0.31622777]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.9486833 ]]
Vector 2: [[0.30151134]
 [0.        ]
 [0.        ]
 [0.30151134]
 [0.90453403]]
Vector 3: [[0.        ]
 [0.30151134]
 [0.        ]
 [0.30151134]
 [0.90453403]]
Vector 4: [[0.        ]
 [0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]
Problem 3: Matrix A using basis as columns:
 [[1 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 1 1]
 [3 3 3 0]]
Problem 4: Matrix B using basis as columns:
 [[1 0 0 0 3]
 [1 0 0 1 3]
 [0 1 0 1 3]
 [0 0 1 1 0]]
Problem 5: Null space of A is trivial (only zero vector)
Null space of B:
 [[-6.88247202e-01]
 [-6.88247202e-01]
 [ 4.95674492e-16]
 [-5.55111512e-16]
 [ 2.29415734e-01]]
Problem 6: Columns of A are independent
Problem 7: Columns of B are dependent
Problem 8: Dimension of null space of A: 0
Problem 8: Dimension of null space of B: 1
Problem 9: Rank of A: 4
Problem 9: Rank of B: 4


In [18]:
#6
basis_vectors = [
    np.array([[0, 1, 0, 0, 3]]).T,
    np.array([[3, 0, 0, 2, 0]]).T
]
y = np.array([[0, 0, 1, 1, 6]]).T

solve(basis_vectors, y)


Problem 1: Is y in the span of the basis vectors? False
Problem 2: Normalized basis vectors:
Vector 1: [[0.        ]
 [0.31622777]
 [0.        ]
 [0.        ]
 [0.9486833 ]]
Vector 2: [[0.83205029]
 [0.        ]
 [0.        ]
 [0.5547002 ]
 [0.        ]]
Problem 3: Matrix A using basis as columns:
 [[0 3]
 [1 0]
 [0 0]
 [0 2]
 [3 0]]
Problem 4: Matrix B using basis as columns:
 [[0 1 0 0 3]
 [3 0 0 2 0]]
Problem 5: Null space of A is trivial (only zero vector)
Null space of B:
 [[ 0.         -0.5042683  -0.23109693]
 [ 0.          0.39523656 -0.86243148]
 [ 1.          0.          0.        ]
 [ 0.          0.75640245  0.34664539]
 [ 0.         -0.13174552  0.28747716]]
Problem 6: Columns of A are independent
Problem 7: Columns of B are dependent
Problem 8: Dimension of null space of A: 0
Problem 8: Dimension of null space of B: 3
Problem 9: Rank of A: 2
Problem 9: Rank of B: 2
