In [3]:
import numpy as np
from numpy import ones
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from numpy import genfromtxt
from numpy import mean
from numpy.random import randn
import scipy.optimize
from scipy.integrate import quad
import scipy.stats as stats
from scipy.stats import expon
from scipy.stats import norm
import pandas as pd
import sys
np.set_printoptions(precision=4)
np.set_printoptions(threshold=30)
np.set_printoptions(linewidth=300)
np.set_printoptions(suppress=True)
np.set_printoptions(threshold=sys.maxsize)
from sklearn.metrics import accuracy_score
from sklearn.metrics.pairwise import rbf_kernel

In [8]:
X = np.array([[1,2], [0,1], [1,0]])
K = rbf_kernel(X, gamma=1)
print(K)

[[1.     0.1353 0.0183]
 [0.1353 1.     0.1353]
 [0.0183 0.1353 1.    ]]


In [20]:
X = np.array([[0.5,0.2], [0,0], [3,1], [4,1]])
K = rbf_kernel(X, gamma=0.1)
D, V = np.linalg.eigh(K)
print(V)
U = V
U_hat = []
for row in U:
  U_hat.append(row/np.linalg.norm(row))
np.array(U_hat)
print(U_hat)





[[-0.6958 -0.204  -0.4337 -0.535 ]
 [ 0.601   0.3514 -0.5229 -0.4918]
 [ 0.328  -0.6556  0.4312 -0.5261]
 [-0.217   0.6365  0.5938 -0.4418]]
[array([-0.6958, -0.204 , -0.4337, -0.535 ]), array([ 0.601 ,  0.3514, -0.5229, -0.4918]), array([ 0.328 , -0.6556,  0.4312, -0.5261]), array([-0.217 ,  0.6365,  0.5938, -0.4418])]
