In [3]:
import numpy as np
from numpy import ones
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from numpy import genfromtxt
from numpy import mean
from numpy.random import randn
import scipy.optimize
from scipy.integrate import quad
import scipy.stats as stats
from scipy.stats import expon
from scipy.stats import norm
import pandas as pd
import sys
np.set_printoptions(precision=4)
np.set_printoptions(threshold=30)
np.set_printoptions(linewidth=300)
np.set_printoptions(suppress=True)
np.set_printoptions(threshold=sys.maxsize)

In [4]:
def closed_form(A,y):
  return np.linalg.inv(A.T.dot(A)).dot(A.T).dot(y)

A = np.array([[0,0,2],
              [0,2,-1],
              [2,-1,0]])
y = np.array([[-3,0,2]]).T
print(closed_form(A,y))

[[ 0.625]
 [-0.75 ]
 [-1.5  ]]


In [5]:
def obj(x):
  return 2*x**2 + 1
def g(x):
  return -(x - 1)
constraints = [{'type': 'ineq', 'fun': g}]
result = scipy.optimize.minimize(obj, -2, constraints = constraints)
print(result)

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 1.0
       x: [-4.967e-09]
     nit: 3
     jac: [ 1.490e-08]
    nfev: 6
    njev: 3


In [6]:
def obj(x):
  return x[0] + 4 * x[1]**2
def h(x):
  return x[0]**2 - 5*x[0] + 4
def g(x):
  return -(1 - x[1])
constraints = [{'type': 'ineq', 'fun': g}, {'type': 'eq', 'fun': h}]
result = scipy.optimize.minimize(obj, np.array([2,2]).T, constraints = constraints)
print(result)

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 4.999999999301984
       x: [ 1.000e+00  1.000e+00]
     nit: 6
     jac: [ 1.000e+00  8.000e+00]
    nfev: 18
    njev: 6


In [7]:
def obj(x):
  return 1/2*x[0]**2 + x[1]**2
def g1(x):
  return (x[1] - 1)
def g2(x):
  return (x[0]-3*x[1])
constraints = [{'type': 'ineq', 'fun': g1}, {'type': 'ineq', 'fun': g2}]
result = scipy.optimize.minimize(obj, np.array([2,2]).T, constraints = constraints)
print(result)

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 5.499999999999947
       x: [ 3.000e+00  1.000e+00]
     nit: 2
     jac: [ 3.000e+00  2.000e+00]
    nfev: 6
    njev: 2


In [18]:
A = np.array([[1,-1],
              [2,3]])
B = np.array([[1,3],
              [2,-5]])
x = np.array([[1, 0]]).T
print (A@x)
print (A@B)

[[1]
 [2]]
[[-1  8]
 [ 8 -9]]
